name: xml2json
version: 1.0.0
author: S. Hamblett
description: An XML to JSON conversion package.
homepage: https://github.com/shamblett/xml2json
documentation: https://github.com/shamblett/xml2json
dependencies:
  browser: any
  petitparser: any
dev_dependencies:
  json: any
  meta: any
  unittest: any
