name: xml2json
version: 4.4.0
description: An XML to JSON conversion package. Supports Badgerfish, GData and Parker conversions.
homepage: https://github.com/shamblett/xml2json

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  xml: '^4.2.0'

dev_dependencies:
  test: '^1.15.4'
  pedantic: '^1.9.1'
  pana: '^0.14.4'
  build_runner: '^1.10.2'
  build_test: '^1.2.0'
  build_web_compilers: '^2.11.0'