name: xml2json
version: 4.4.0
description: An XML to JSON conversion package. Supports Badgerfish, GData and Parker conversions.
homepage: https://github.com/shamblett/xml2json

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  xml: '^4.5.1'

dev_dependencies:
  test: '^1.15.7'
  pedantic: '^1.9.2'
  pana: '^0.14.9'
  build_runner: '^1.11.1'
  build_test: '^1.3.6'
  build_web_compilers: '^2.12.2'