name: xml2json
version: 2.0.11
author: S. Hamblett <steve.hamblett@linux.com>
description: An XML to JSON conversion package. Supports Badgerfish, GData and Parker conversions.
homepage: https://github.com/shamblett/xml2json

environment:
  sdk: ">=1.8.0  <2.0.0-dev.infinity"

dependencies:
  xml: '>=2.2.0 <3.0.0'

dev_dependencies:
  test: '^0.12.9'
  coverage: '^0.7.3'
  dart_dev: '^1.0.0'
  dart_style: '>=0.2.0 <0.3.0'
  dartdoc: '>=0.8.0 <=0.10.0'