name: xml2json
author: S. Hamblett <steve.hamblett@linux.com>
version: 2.0.1
homepage: https://github.com/shamblett/xml2json
description: An XML to JSON conversion package.
documentation: http://oscf.org.uk/dart/api/xml2json/xml2json/Xml2Json.html
dependencies:
  browser: any
  petitparser: '>=1.0.1'
dev_dependencies:
  meta: any
  unittest: any
