name: xml2json
version: 2.0.9
author: S. Hamblett <steve.hamblett@linux.com>
description: An XML to JSON conversion package.
homepage: https://github.com/shamblett/xml2json

environment:
  sdk: ">=1.8.0  <2.0.0-dev.infinity"

dependencies:
  xml: '>=2.2.0 <2.3.0'

dev_dependencies:
  browser: '>=0.9.1 <0.10.0'
  meta: any
  test: '^0.12.9'
